import { z } from 'zod';
import { ServiceType, PaymentType, ShipmentStatus, FailureReason } from '../enums.js';
export declare const createShipmentSchema: z.ZodEffects<z.ZodObject<{
    senderName: z.ZodString;
    senderPhone: z.ZodString;
    senderAddress: z.ZodString;
    senderCity: z.ZodString;
    senderAddressExtra: z.ZodOptional<z.ZodString>;
    receiverName: z.ZodString;
    receiverPhone: z.ZodString;
    receiverAddress: z.ZodString;
    receiverCity: z.ZodString;
    receiverAddressExtra: z.ZodOptional<z.ZodString>;
    originHubId: z.ZodOptional<z.ZodString>;
    destinationHubId: z.ZodOptional<z.ZodString>;
    serviceType: z.ZodDefault<z.ZodNativeEnum<typeof ServiceType>>;
    paymentType: z.ZodNativeEnum<typeof PaymentType>;
    codAmount: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    packageType: z.ZodString;
    weightKg: z.ZodNumber;
    lengthCm: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    widthCm: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    heightCm: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    declaredValue: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    isFragile: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    senderName: string;
    senderPhone: string;
    senderAddress: string;
    senderCity: string;
    receiverName: string;
    receiverPhone: string;
    receiverAddress: string;
    receiverCity: string;
    serviceType: ServiceType;
    paymentType: PaymentType;
    packageType: string;
    weightKg: number;
    isFragile: boolean;
    senderAddressExtra?: string | undefined;
    receiverAddressExtra?: string | undefined;
    originHubId?: string | undefined;
    destinationHubId?: string | undefined;
    codAmount?: number | null | undefined;
    lengthCm?: number | null | undefined;
    widthCm?: number | null | undefined;
    heightCm?: number | null | undefined;
    description?: string | null | undefined;
    declaredValue?: number | null | undefined;
}, {
    senderName: string;
    senderPhone: string;
    senderAddress: string;
    senderCity: string;
    receiverName: string;
    receiverPhone: string;
    receiverAddress: string;
    receiverCity: string;
    paymentType: PaymentType;
    packageType: string;
    weightKg: number;
    senderAddressExtra?: string | undefined;
    receiverAddressExtra?: string | undefined;
    originHubId?: string | undefined;
    destinationHubId?: string | undefined;
    serviceType?: ServiceType | undefined;
    codAmount?: number | null | undefined;
    lengthCm?: number | null | undefined;
    widthCm?: number | null | undefined;
    heightCm?: number | null | undefined;
    description?: string | null | undefined;
    declaredValue?: number | null | undefined;
    isFragile?: boolean | undefined;
}>, {
    senderName: string;
    senderPhone: string;
    senderAddress: string;
    senderCity: string;
    receiverName: string;
    receiverPhone: string;
    receiverAddress: string;
    receiverCity: string;
    serviceType: ServiceType;
    paymentType: PaymentType;
    packageType: string;
    weightKg: number;
    isFragile: boolean;
    senderAddressExtra?: string | undefined;
    receiverAddressExtra?: string | undefined;
    originHubId?: string | undefined;
    destinationHubId?: string | undefined;
    codAmount?: number | null | undefined;
    lengthCm?: number | null | undefined;
    widthCm?: number | null | undefined;
    heightCm?: number | null | undefined;
    description?: string | null | undefined;
    declaredValue?: number | null | undefined;
}, {
    senderName: string;
    senderPhone: string;
    senderAddress: string;
    senderCity: string;
    receiverName: string;
    receiverPhone: string;
    receiverAddress: string;
    receiverCity: string;
    paymentType: PaymentType;
    packageType: string;
    weightKg: number;
    senderAddressExtra?: string | undefined;
    receiverAddressExtra?: string | undefined;
    originHubId?: string | undefined;
    destinationHubId?: string | undefined;
    serviceType?: ServiceType | undefined;
    codAmount?: number | null | undefined;
    lengthCm?: number | null | undefined;
    widthCm?: number | null | undefined;
    heightCm?: number | null | undefined;
    description?: string | null | undefined;
    declaredValue?: number | null | undefined;
    isFragile?: boolean | undefined;
}>;
export type CreateShipmentInput = z.infer<typeof createShipmentSchema>;
export declare const updateShipmentSchema: z.ZodObject<{
    senderName: z.ZodOptional<z.ZodString>;
    senderPhone: z.ZodOptional<z.ZodString>;
    senderAddress: z.ZodOptional<z.ZodString>;
    senderCity: z.ZodOptional<z.ZodString>;
    senderAddressExtra: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    receiverName: z.ZodOptional<z.ZodString>;
    receiverPhone: z.ZodOptional<z.ZodString>;
    receiverAddress: z.ZodOptional<z.ZodString>;
    receiverCity: z.ZodOptional<z.ZodString>;
    receiverAddressExtra: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    packageType: z.ZodOptional<z.ZodString>;
    weightKg: z.ZodOptional<z.ZodNumber>;
    lengthCm: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    widthCm: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    heightCm: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    declaredValue: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    isFragile: z.ZodOptional<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    senderName?: string | undefined;
    senderPhone?: string | undefined;
    senderAddress?: string | undefined;
    senderCity?: string | undefined;
    senderAddressExtra?: string | null | undefined;
    receiverName?: string | undefined;
    receiverPhone?: string | undefined;
    receiverAddress?: string | undefined;
    receiverCity?: string | undefined;
    receiverAddressExtra?: string | null | undefined;
    packageType?: string | undefined;
    weightKg?: number | undefined;
    lengthCm?: number | null | undefined;
    widthCm?: number | null | undefined;
    heightCm?: number | null | undefined;
    description?: string | null | undefined;
    declaredValue?: number | null | undefined;
    isFragile?: boolean | undefined;
}, {
    senderName?: string | undefined;
    senderPhone?: string | undefined;
    senderAddress?: string | undefined;
    senderCity?: string | undefined;
    senderAddressExtra?: string | null | undefined;
    receiverName?: string | undefined;
    receiverPhone?: string | undefined;
    receiverAddress?: string | undefined;
    receiverCity?: string | undefined;
    receiverAddressExtra?: string | null | undefined;
    packageType?: string | undefined;
    weightKg?: number | undefined;
    lengthCm?: number | null | undefined;
    widthCm?: number | null | undefined;
    heightCm?: number | null | undefined;
    description?: string | null | undefined;
    declaredValue?: number | null | undefined;
    isFragile?: boolean | undefined;
}>;
export type UpdateShipmentInput = z.infer<typeof updateShipmentSchema>;
export declare const statusTransitionSchema: z.ZodObject<{
    toStatus: z.ZodNativeEnum<typeof ShipmentStatus>;
    hubId: z.ZodOptional<z.ZodString>;
    note: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    toStatus: ShipmentStatus;
    hubId?: string | undefined;
    note?: string | undefined;
}, {
    toStatus: ShipmentStatus;
    hubId?: string | undefined;
    note?: string | undefined;
}>;
export type StatusTransitionInput = z.infer<typeof statusTransitionSchema>;
export declare const deliverShipmentSchema: z.ZodObject<{
    recipientName: z.ZodOptional<z.ZodString>;
    note: z.ZodOptional<z.ZodString>;
    proofImageUrl: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    amountCollected: z.ZodOptional<z.ZodNumber>;
    discrepancyNote: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    note?: string | undefined;
    recipientName?: string | undefined;
    proofImageUrl?: string | null | undefined;
    amountCollected?: number | undefined;
    discrepancyNote?: string | undefined;
}, {
    note?: string | undefined;
    recipientName?: string | undefined;
    proofImageUrl?: string | null | undefined;
    amountCollected?: number | undefined;
    discrepancyNote?: string | undefined;
}>;
export type DeliverShipmentInput = z.infer<typeof deliverShipmentSchema>;
export declare const deliveryFailureSchema: z.ZodEffects<z.ZodObject<{
    reason: z.ZodNativeEnum<typeof FailureReason>;
    note: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    reason: FailureReason;
    note?: string | undefined;
}, {
    reason: FailureReason;
    note?: string | undefined;
}>, {
    reason: FailureReason;
    note?: string | undefined;
}, {
    reason: FailureReason;
    note?: string | undefined;
}>;
export type DeliveryFailureInput = z.infer<typeof deliveryFailureSchema>;
//# sourceMappingURL=shipment.d.ts.map